from MODES import DIGCLASS, SAFECLASS, STOPCLASS, SLEEPCLASS, COMMONFUNCS


DIGMaster = DIGCLASS()
SAFEMaster = SAFECLASS()
STOPMaster = STOPCLASS()
SLEEPMaster = SLEEPCLASS()
commonFunc = COMMONFUNCS()
